# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b777abd5a6bdd4013e91f67eb3245e7dbe16f3d4dde30c3fbdc9cf906714b8c51db7142a99e3abf64050e1057424700e569eb7127c436ebf51f614dbdfd67de2

test:
  secret_key_base: 22e23762bf9546c9c04cd098fd8c3bda04ddd9a141dfca45c82f75139a25c4a1bd0a03c17aace60b45bad2ff560ab238ed1e350e9e1a145376fb8e276f21129e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
